_target_: ami.checkpointing.checkpoint_schedulers.FixedTimeIntervalCheckpointScheduler

checkpointing:
  _target_: ami.checkpointing.checkpointing.Checkpointing

  checkpoints_dir: ${paths.checkpoints_dir}

interval: 43200.0 # 12h
