_target_: ami.interactions.agents.curiosity_image_ppo_agent.CuriosityImagePPOAgent

initial_hidden:
  _target_: torch.zeros
  _args_:
    - ${models.forward_dynamics.model.core_model.depth}
    - ${models.forward_dynamics.model.core_model.dim}
  dtype: ${torch.dtype:cfloat}
