_target_: ami.interactions.agents.multi_step_imagination_curiosity_agent.MultiStepImaginationCuriosityImageAgent

initial_hidden:
  _target_: torch.zeros
  _args_:
    - ${models.forward_dynamics.model.core_model.depth}
    - ${models.forward_dynamics.model.core_model.dim}
  dtype: ${torch.dtype:float}

logger:
  _target_: ami.tensorboard_loggers.TimeIntervalLogger
  log_dir: ${paths.tensorboard_dir}/agent
  log_every_n_seconds: 0

max_imagination_steps: 10
