_target_: ami.interactions.agents.curiosity_image_ppo_agent.CuriosityImagePPOAgent

initial_hidden:
  _target_: torch.zeros
  _args_:
    - ${models.forward_dynamics.model.core_model.depth}
    - ${models.forward_dynamics.model.core_model.dim}
  dtype: ${torch.dtype:cfloat}

logger:
  _target_: ami.tensorboard_loggers.TimeIntervalLogger
  log_dir: ${paths.tensorboard_dir}/agent
  log_every_n_seconds: 0

reward:
  _target_: ami.interactions.agents.curiosity_image_ppo_agent.PredictionErrorReward
  scale: 0.001
  shift: 0.0
