services:
  ami:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${USER}/ami:latest
    volumes:
      - ami:/workspace
      - ./logs:/workspace/logs
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    tty: true
    stdin_open: true

  ami-host:
    extends:
      service: ami
    devices:
      - "${WEBCAM_DEVICE:-/dev/video0}:/dev/video0:mwr"
    volumes:
      - ami:/workspace
      - ./logs:/workspace/logs
      - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
      - ~/.config/pulse/cookie:/root/.config/pulse/cookie
    environment:
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
      - PULSE_COOKIE=/root/.config/pulse/cookie

  ami-unity:
    extends:
      service: ami
    volumes:
      - ami:/workspace
      - ./logs:/workspace/logs
      - ./unity_executables:/workspace/unity_executables:ro

  ami-data:
    extends:
      service: ami
    volumes:
      - ami:/workspace
      - ./logs:/workspace/logs
      - ${DATA_DIR:-./data}:/workspace/data:ro

volumes:
  ami:
    name: ami-${USER}
