# You can specify configuration values that are shared among all config files.

image_height: 84
image_width: 84
image_channels: 3

audio_sample_rate: 16000
audio_channel_size: 2
audio_sample_size: 16080
