_target_: ami.trainers.bool_mask_audio_jepa_trainer.BoolMaskAudioJEPATrainer

partial_dataloader:
  _target_: torch.utils.data.DataLoader
  _partial_: true
  batch_size: 32
  shuffle: true
  drop_last: true # for batchnorm.
  # based on the original paper settings
  collate_fn:
    _target_: ami.trainers.components.bool_audio_jepa_mask_collator.BoolAudioJEPAMultiBlockMaskCollator
    input_sample_size: ${models.audio_jepa_target_encoder.model.input_sample_size}
    patch_sample_size: 400
    stride: 320
    mask_scale: [0.1, 0.25]
    n_masks: 4
    min_keep: 5

# based on the original paper's initial params
partial_optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0001
  weight_decay: 0.04

logger:
  _target_: ami.tensorboard_loggers.StepIntervalLogger
  log_dir: ${paths.tensorboard_dir}/audio_jepa
  log_every_n_steps: 1

device: ${devices.0}
max_epochs: 3
minimum_dataset_size: ${.partial_dataloader.batch_size}
minimum_new_data_count: 128 # From primitive ami.
target_encoder_update_moving_average: 0.996
