_target_: ami.interactions.environments.dummy_environment.DummyEnvironment

observation_generator:
  _target_: ami.interactions.environments.audio_observation_generator.AudioFilesObservationGenerator
  audio_files: ??? # Please specify dataset dir.
  chunk_size: ${shared.audio_sample_size}
  stride: ${python.eval":int(${shared.audio_sample_rate} * 0.1)"}
  sample_rate: ${shared.audio_sample_rate}
  max_frames_per_file: null

action_checker:
  _target_: ami.interactions.environments.dummy_environment.ActionTypeChecker
  action_type:
    _target_: hydra.utils.get_class
    path: torch.Tensor
