_target_: ami.interactions.environments.dummy_environment.DummyEnvironment
observation_generator:
  _partial_: true
  _target_: torch.zeros
  _args_:
    - ${shared.image_channels}
    - ${shared.image_height}
    - ${shared.image_width}

action_checker:
  _target_: ami.interactions.environments.dummy_environment.ActionTypeChecker
  action_type:
    _target_: hydra.utils.get_class
    path: torch.Tensor
