_target_: ami.interactions.environments.dummy_environment.DummyEnvironment

observation_generator:
  _partial_: true
  _target_: torch.zeros
  _args_:
    - ${shared.audio_channel_size}
    - ${shared.audio_sample_size}

action_checker:
  _target_: ami.interactions.environments.dummy_environment.ActionTypeChecker
  action_type:
    _target_: hydra.utils.get_class
    path: torch.Tensor
