defaults:
  - bool_mask_i_jepa

i_jepa_target_encoder:
  model:
    patch_size: 12
    embed_dim: 432
    out_dim: 32
    depth: 9
    num_heads: 6
i_jepa_predictor:
  model:
    hidden_dim: 216
    depth: 9
    num_heads: 3
