# Hyper params following set based on original I-JEPA's "vit_base"
i_jepa_encoder:
  _target_: ami.models.model_wrapper.ModelWrapper
  default_device: ${devices.0}
  has_inference: True
  model:
    _target_: ami.models.i_jepa.IJEPAEncoder
    img_size: 224
    patch_size: 16
    embed_dim: 768
    depth: 12
    num_heads: 12
    mlp_ratio: 4.0

i_jepa_predictor:
  _target_: ami.models.model_wrapper.ModelWrapper
  default_device: ${devices.0}
  has_inference: False
  model:
    _target_: ami.models.i_jepa.IJEPAPredictor
    n_patches: [14, 14]
    context_encoder_embed_dim: 768
    predictor_embed_dim: 384
    depth: 6
    num_heads: 12
