_version_: 2 # Instantiation Method Version.

_target_: ami.models.instantiations.image_vae
device: ${devices.0}
height: ${shared.image_height}
width: ${shared.image_width}
channels: ${shared.image_channels}
latent_dim: 512
