_target_: ami.trainers.dreaming_policy_value_trainer.DreamingPolicyValueTrainer

partial_dataloader:
  _target_: torch.utils.data.DataLoader
  _partial_: true
  batch_size: 128
  shuffle: false
  drop_last: true

partial_policy_optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-4
  betas: [0.9, 0.999]

partial_value_optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-4
  betas: [0.9, 0.999]

partial_policy_lr_scheduler:
  _target_: ami.trainers.dreaming_policy_value_trainer.InitialMultiplicationLRScheduler
  _partial_: true
  multiplication_factor: 0.0
  initial_epochs: ${python.eval:"50 * ${..max_epochs}"} # 大体10分くらい。
  verbose: true

partial_value_lr_scheduler:
  _target_: ami.trainers.dreaming_policy_value_trainer.InitialMultiplicationLRScheduler
  _partial_: true
  multiplication_factor: 0.0
  initial_epochs: ${python.eval:"50 * ${..max_epochs}"} # 大体10分くらい。
  verbose: true

logger:
  _target_: ami.tensorboard_loggers.StepIntervalLogger
  log_dir: ${paths.tensorboard_dir}/forward_dynamics
  log_every_n_steps: 1

device: ${devices.0}
max_epochs: 1
imagination_trajectory_length: 25
imagination_temperature: 1.0
minimum_dataset_size: ${.partial_dataloader.batch_size}
minimum_new_data_count: ${.partial_dataloader.batch_size}
