root:
  handlers: [root_console, root_file]

loggers:
  main:
    handlers: [main_file]
  training:
    handlers: [training_file]
  inference:
    handlers: [inference_file]

handlers:
  root_console:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    level: DEBUG
    formatter: simple

  root_file:
    class: logging.handlers.TimeRotatingFileHandler
    filename: logs/root/root.log
    when: D
    level: DEBUG
    formatter: simple

  main_file:
    class: logging.handlers.TimeRotatingFileHandler
    filename: logs/main/main.log
    when: D
    level: DEBUG
    formatter: simple

  training_file:
    class: logging.handlers.TimeRotatingFileHandler
    filename: logs/training/training.log
    when: D
    level: DEBUG
    formatter: simple

  inference_file:
    class: logging.handlers.TimeRotatingFileHandler
    filename: logs/inference/inference.log
    when: D
    level: DEBUG
    formatter: simple

formatters:
  simple:
    format: "%(asctime)s %(levelname).4s %(name).16s | %(message)s"

version: 1
