main_thread:
  _target_: ami.threads.main_thread.MainThread
  address: ["0.0.0.0", 8391]
  max_uptime: ${python.eval:"float('${max_uptime}')"}

inference_thread:
  _target_: ami.threads.inference_thread.InferenceThread

training_thread:
  _target_: ami.threads.training_thread.TrainingThread
