_target_: ami.trainers.ppo_policy_trainer.PPOTemporalPolicyTrainer

partial_dataloader:
  _target_: torch.utils.data.DataLoader
  _partial_: true

partial_sampler:
  _target_: ami.trainers.components.random_time_series_sampler.RandomTimeSeriesSampler
  _partial_: true
  sequence_length: 8
  max_samples: 256 # For dataset size 2048

partial_optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-4
  betas: [0.9, 0.999]

logger:
  _target_: ami.tensorboard_loggers.StepIntervalLogger
  log_dir: ${paths.tensorboard_dir}/ppo_policy
  log_every_n_steps: 1

device: ${devices.0}
max_epochs: 3
minimum_dataset_size: ${.partial_sampler.sequence_length}
minimum_new_data_count: 128
entropy_coef: 0.0
