# @package models

defaults:
  - temporal/no_action.yaml

multimodal_temporal_encoder:
  model:
    core_model:
      depth: 12
      dim: 1024
      dim_ff_hidden: ${python.eval:"${.dim} * 4"}

forward_dynamics:
  model:
    core_model:
      depth: 30
      dim: 1024
      dim_ff_hidden: ${python.eval:"${.dim} * 4"}
