# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - interaction: default
  - data_collectors: image
  - models: image_vae
  - trainers: image_vae
  - threads: default

  - devices: cuda
  - paths: default
  - hydra: default

  # experiment configs allow for version control of specific hyperparameters
  - experiment: null

task_name: image_encoding
