# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_

  - interaction: default
  - data_collectors: image
  - models: image_vae
  - trainers: image_vae
  - threads: default

  - checkpointing: default
  - devices: cuda
  - paths: default
  - hydra: default

  # You can specify configuration values that are shared among all config files.
  - shared: default

  # experiment configs allow for version control of specific hyperparameters
  - experiment: null

task_name: image_encoding
subtask_name: "" # if given, create subfolder under the task_name
task_tag: "default" # Running tags

# You can specify saved checkpoint path when system is begun.
saved_checkpoint_path: null

# You can specify `hydra.job_logging.root.level`
log_level: INFO

# You can specify the time scale for the experiment.
time_scale: 1.0

max_uptime: inf # This value will scale by `time_scale`.

torch_float32_matmul_precision: "high" # Using tensor core.

torch_cudnn_benchmark: True # Performance up on the cuda.

torch_default_dtype: ${torch.dtype:float32}

torch_default_device: ${devices.0}
