_target_: ami.trainers.forward_dynamics_trainer.ForwardDynamicsTrainer

partial_dataloader:
  _target_: torch.utils.data.DataLoader
  _partial_: true
  batch_size: ${python.eval:8+1} # To generate future target data.
  shuffle: false
  drop_last: true # To avoid zero length tensor

partial_optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-4
  betas: [0.9, 0.999]

observation_encoder_name: image_encoder
device: ${devices.0}
max_epochs: 3
minimum_dataset_size: ${.partial_dataloader.batch_size}
