_target_: ami.trainers.forward_dynamics_trainer.ImaginingForwardDynamicsTrainer

partial_dataloader:
  _target_: torch.utils.data.DataLoader
  _partial_: true

partial_sampler:
  _target_: ami.trainers.components.random_time_series_sampler.RandomTimeSeriesSampler
  _partial_: true
  max_samples: 256 # For dataset size 2048

partial_optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-4
  betas: [0.9, 0.999]

logger:
  _target_: ami.tensorboard_loggers.StepIntervalLogger
  log_dir: ${paths.tensorboard_dir}/forward_dynamics
  log_every_n_steps: 1

observation_encoder_name: image_encoder
device: ${devices.0}
max_epochs: 3
sequence_length: 8
imagination_length: 1
minimum_new_data_count: 128 # From primitive AMI
gradient_clip_norm: null
