forward_dynamics_trajectory:
  _target_: ami.data.buffers.causal_data_buffer.CausalDataBuffer.reconstructable_init
  max_len: 2048
  key_list:
    - "observation"
    - "hidden"
    - "action"
    - "reward"
