_target_: ami.data.utils.DataCollectorsDict.from_data_buffers

image:
  _target_: ami.data.buffers.random_data_buffer.RandomDataBuffer
  max_len: 2048 # From Primitive AMI.
  key_list:
    - "observation"
