_target_: ami.trainers.multimodal_temporal_encoder_trainer.MultimodalTemporalEncoderTrainer

partial_dataloader:
  _target_: torch.utils.data.DataLoader
  _partial_: true
  shuffle: false
  collate_fn:
    _target_: hydra.utils.get_method
    path: ami.trainers.components.transpose_and_stack_collator.transpose_and_stack_collator

partial_sampler:
  _target_: ami.trainers.components.random_time_series_sampler.RandomTimeSeriesSampler
  _partial_: true
  sequence_length: ${python.eval:"8 + 1"} # +1 to generate future target data.
  max_samples: 256 # For dataset size 2048

partial_optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-4
  betas: [0.9, 0.999]

logger:
  _target_: ami.tensorboard_loggers.StepIntervalLogger
  log_dir: ${paths.tensorboard_dir}/mulitmodal_temporal
  log_every_n_steps: 1

device: ${devices.0}
minimum_dataset_size: ${.partial_sampler.sequence_length}
